### ISSUE TITLE
Ability to not have a Game class

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/MonoMyst#10]
Right now you have to have a game class that inherits `MGame`. And basically all it does it change some settings and run the scene. Would be better if the game could be defined in a yaml file like so:

`Game.mma` file:
```yaml
---
Title: Game Title

Resolution:
  - Width: 1280
  - Height: 720

MainScene: MainSceneName
...
```

And the main scene asset file should also be defined. Related to: #6 

Of course you could also have a Game class if you want.
